version: '3'
services:
  ts-node-api:
    container_name: ts-node-api
    build: .
    dns_search: ''
    restart: always
    volumes:     
      - ./src/:/app/src
    ports:
      - "3060:3060"
    depends_on:
      - mongodb
    links:
      - mongodb
    command: sh -c "npm run debug"

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
